name: Deploy Android App to Play Store

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: ['deploy-android-to-play-store']

env:
  RUBY_VERSION: '3.4.2'
  NODE_VERSION: '24'
  JAVA_VERSION: '21'
  XCODE_VERSION: '26.2'
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  deploy-android-to-play-store:
    name: Deploy Android App to Play Store
    runs-on: ubuntu-24.04
    steps:
#      - name: Delete huge unnecessary tools folder
#        run: rm -rf /opt/hostedtoolcache

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/initial-setup
        with:
          java: ${{ env.JAVA_VERSION }}
          ruby: ${{ env.RUBY_VERSION }}

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}

      - uses: ./.github/actions/install-dependencies
        with:
          no-cache: 'true'

      - uses: ./.github/actions/android-keystores
        with:
          encrypt-password: ${{ secrets.ENCRYPT_PASSWORD }}

      - name: Clean before Fastlane
        run: |
          rm -rf node_modules/.cache
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches
          df -h

      - name: Run fastlane line "fastlane android deploy" with PROD ENV variables
        run: bundle exec fastlane android deploy
        env:
          # sentry
          SENTRY_PROPERTIES: ./android/sentry.properties
          # app env variables
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY_STAGING }}
          APP_METRICA_API_KEY: ${{ secrets.APP_METRICA_API_KEY_STAGING }}
          DATABASE_DEFAULT_ENCRYPTION_KEY: ${{ secrets.DATABASE_DEFAULT_ENCRYPTION_KEY }}
          OAUTH_CLIENT_ID_ANDROID: ${{ secrets.OAUTH_CLIENT_ID_ANDROID_STAGING }}
          OAUTH_CLIENT_ID_IOS: ${{ secrets.OAUTH_CLIENT_ID_IOS_STAGING }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
          REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}
          TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
          TIKTOK_APP_ID: ${{ secrets.TIKTOK_APP_ID }}
          # Fastlane env variables
          BUMP_TYPE: ${{ github.event.client_payload.bump_type }}
