name: Deploy iOS App to Test Flight

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: ['deploy-ios-to-test-flight']

jobs:
  deploy-ios-to-test-flight:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-26 ]
        # ^^^ macos-26 Installed Software: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
        ruby: [ '3.4.2' ]
        nodejs: [ '24' ]
        xcode: [ '26.2' ]
        # ^^^ See all Xcode versions (for macos-26): https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md#xcode

    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_STEP_DEBUG: true
      NODE_OPTIONS: --max_old_space_size=4096

    steps:
      - uses: ./.github/actions/initial-setup
        with:
          ruby: ${{ matrix.ruby }}
          nodejs: ${{ matrix.nodejs }}
          xcode: ${{ matrix.xcode }}

      - name: Switch to Java 8 (hack for uploading build to Test Flight)
        run: |
            java -version
            cd /Library/Java/JavaVirtualMachines
            rm -rf openjdk-11.0.1.jdk
            java -version

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}
          depth: 1

      - uses: ./.github/actions/install-dependencies
        with:
          no-cache: 'true'

      - name: Install gem dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Install pods
        run: yarn pod-install

      - name: Run fastlane line "fastlane ios deploy" with PROD ENV variables
        run: bundle exec fastlane ios deploy
        env:
          # sentry
          SENTRY_ALLOW_FAILURE: ${{ secrets.SENTRY_ALLOW_FAILURE }}
          SENTRY_PROPERTIES: ${{ github.workspace }}/ios/sentry.properties
          # app env variables
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          APPSFLYER_API_KEY: ${{ secrets.APPSFLYER_API_KEY }}
          APP_METRICA_API_KEY: ${{ secrets.APP_METRICA_API_KEY }}
          DATABASE_DEFAULT_ENCRYPTION_KEY: ${{ secrets.DATABASE_DEFAULT_ENCRYPTION_KEY }}
          OAUTH_CLIENT_ID_ANDROID: ${{ secrets.OAUTH_CLIENT_ID_ANDROID }}
          OAUTH_CLIENT_ID_IOS: ${{ secrets.OAUTH_CLIENT_ID_IOS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
          REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}
          TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
          TIKTOK_APP_ID: ${{ secrets.TIKTOK_APP_ID }}
          # Fastlane env variables
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          BUMP_TYPE: ${{ github.event.client_payload.bump_type }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
