name: new Distribute IPA to Firebase App Distribution

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: ['distribute-ipa-new']

jobs:
  distribute-ipa:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-26 ]
        # ^^^ macos-26 Installed Software: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
        ruby: [ '3.4.2' ]
        nodejs: [ '24' ]
        xcode: [ '26.2' ]
        # ^^^ See all Xcode versions (for macos-26): https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md#xcode

    runs-on: ${{ matrix.os }}

    env:
      ACTIONS_STEP_DEBUG: true
      NODE_OPTIONS: --max_old_space_size=4096
      # Required by `infrastructure/gitlab/status.sh`
      GIT_LAB_COMMIT_SHA: ${{ github.event.client_payload.commit_sha }}
      GIT_LAB_PIPELINE_ID: ${{ github.event.client_payload.pipeline_id }}

    steps:
    - uses: ./.github/actions/initial-setup
      with:
        ruby: ${{ matrix.ruby }}
        nodejs: ${{ matrix.nodejs }}
        xcode: ${{ matrix.xcode }}

    - uses: ./.github/actions/clone-repo
      with:
        repo-url: ${{ secrets.REPO_URL }}
        user-name: ${{ secrets.GITLAB_USER_NAME }}
        user-email: ${{ secrets.GITLAB_USER_EMAIL }}
        ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        branch: ${{ github.event.client_payload.branch }}

    - name: Notify gitlab
      run: ./infrastructure/gitlab/status.sh "state=running&description=$GITHUB_RUN_ID"
      env:
        GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

    - uses: ./.github/actions/install-dependencies

    - name: Pods cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cocoapods
          ~/Library/Caches/CocoaPods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: ${{ runner.os }}-pods-

    - run: bundle install --jobs 4 --retry 3

    - name: Install pods
      run: yarn pod-install

    - name: iOS build cache
      uses: actions/cache@v4
      with:
        path: .local_derived_data
        key: ${{ runner.os }}-pods-derived-data-${{ hashFiles('ios/Podfile.lock') }}

    - name: Run fastlane line "fastlane ios distribute" with PROD ENV variables
      run: bundle exec fastlane ios distribute
      env:
        BETA_BUILD: true
        # sentry
        SENTRY_DIST: 0
        SENTRY_LOG_LEVEL: debug
        SENTRY_PROPERTIES: ${{ github.workspace }}/ios/sentry.properties
        SENTRY_RELEASE: alpha
        # app env variables
        AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY_STAGING }}
        APPSFLYER_API_KEY: ${{ secrets.APPSFLYER_API_KEY }}
        APP_METRICA_API_KEY: ${{ secrets.APP_METRICA_API_KEY_STAGING }}
        DATABASE_DEFAULT_ENCRYPTION_KEY: ${{ secrets.DATABASE_DEFAULT_ENCRYPTION_KEY }}
        OAUTH_CLIENT_ID_ANDROID: ${{ secrets.OAUTH_CLIENT_ID_ANDROID_STAGING }}
        OAUTH_CLIENT_ID_IOS: ${{ secrets.OAUTH_CLIENT_ID_IOS_STAGING }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
        REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}
        TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
        TIKTOK_APP_ID: ${{ secrets.TIKTOK_APP_ID }}
        # Fastlane env variables
        CURRENT_BRANCH: ${{ github.event.client_payload.branch }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
        FIREBASEAPPDISTRO_APP: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        СUSTOM_BUILD_NUMBER: ${{ github.run_number }}


      #############################################################
      # NOTIFY GITLAB ABOUT JOB RESULT
      #############################################################

    - name: The job has cancelled
      if: ${{ cancelled() }}
      run: ./infrastructure/gitlab/status.sh "state=canceled"
      env:
        GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

    - name: The job has failed
      if: ${{ failure() }}
      run: ./infrastructure/gitlab/status.sh "state=failed"
      env:
        GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}


    - name: The job has success
      run: ./infrastructure/gitlab/status.sh "state=success"
      env:
        GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}
