name: Test All

on:
  repository_dispatch:
    types: ["test-all"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.client_payload.pipeline_id || github.run_id }}
  cancel-in-progress: true

env:
  RUBY_VERSION: '3.4.2'
  NODE_VERSION: '24'
  JAVA_VERSION: '21'
  XCODE_VERSION: '26.2'
  # ^^^ See all Xcode versions (for macos-26): https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md#xcode
  NODE_OPTIONS: --max_old_space_size=4096
  # Required by `infrastructure/gitlab/status.sh`
  GIT_LAB_COMMIT_SHA: ${{ github.event.client_payload.commit_sha }}
  GIT_LAB_PIPELINE_ID: ${{ github.event.client_payload.pipeline_id }}

# macos-26:     CPU: (3) arm64 Apple M1 (Virtual);            Memory: 89.83 MB / 7.00 GB
# ubuntu-24.04: CPU: (4) x64 AMD EPYC 7763 64-Core Processor; Memory: 14.56 GB / 15.62 GB

jobs:
  check_code_changes:
    name: "🔍 Check Code Changes"
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      run_code_quality: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.ts_has_changes == 'true' || steps.can_run.outputs.lint_has_changes == 'true' || steps.can_run.outputs.i18n_has_changes == 'true' || steps.can_run.outputs.test_has_changes == 'true' }}
      run_ts: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.ts_has_changes == 'true' }}
      run_lint: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.lint_has_changes == 'true' }}
      run_i18n: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.i18n_has_changes == 'true' }}
      run_test: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.test_has_changes == 'true' }}
      run_ios_build: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.ios_has_changes == 'true' }}
      run_android_build: ${{ steps.can_run.outcome == 'skipped' || steps.can_run.outputs.android_has_changes == 'true' }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}
      - name: Check for code changes (exclusion & inclusion patterns)
        id: can_run
        if: github.event.client_payload.diff_check && github.event.client_payload.target_branch # target_branch is empty for merged PRs to default branch (so there is nothing to compare with)
        run: node infrastructure/github/check-diff.js ${{ github.event.client_payload.target_branch }}

  code-quality:
    name: "🧪 Code Quality"
    needs: check_code_changes
    if: needs.check_code_changes.outputs.run_code_quality == 'true'
    runs-on: ubuntu-24.04 # macos-26 has when same performance as ubuntu-24.04 for this job
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/actions/initial-setup
        with:
          nodejs: ${{ env.NODE_VERSION }}

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}

      - name: Notify gitlab
        run: ./infrastructure/gitlab/status.sh "state=running&description=$GITHUB_RUN_ID"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

      - uses: ./.github/actions/install-dependencies

      - name: TypeScript
        if: needs.check_code_changes.outputs.run_ts == 'true'
        run: yarn ts

      - name: Eslint
        if: needs.check_code_changes.outputs.run_lint == 'true'
        run: yarn lint --quiet

      - name: Check i18n
        if: needs.check_code_changes.outputs.run_i18n == 'true'
        run: yarn check-i18n

      - name: Unit tests
        if: needs.check_code_changes.outputs.run_test == 'true'
        run: yarn test --ci

      - uses: ./.github/actions/notify-gitlab
        if: always()
        with:
          gitlab-token: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

  distribute-ipa:
    name: "🍎 iOS Build & Distribute"
    needs: check_code_changes
    if: needs.check_code_changes.outputs.run_ios_build == 'true'
    runs-on: macos-26 # macos-26 Installed Software: https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/actions/initial-setup
        with:
          ruby: ${{ env.RUBY_VERSION }}
          nodejs: ${{ env.NODE_VERSION }}
          xcode: ${{ env.XCODE_VERSION }}

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}

      - name: Notify gitlab
        run: ./infrastructure/gitlab/status.sh "state=running&description=$GITHUB_RUN_ID"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

      - uses: ./.github/actions/install-dependencies

      - name: Pods cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cocoapods
            ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - run: bundle install --jobs 4 --retry 3

      - name: Install pods
        run: yarn pod-install

      - name: iOS build cache
        uses: actions/cache@v5
        with:
          path: .local_derived_data
          key: ${{ runner.os }}-pods-derived-data-${{ hashFiles('ios/Podfile.lock') }}

      - name: Run fastlane line "fastlane ios distribute" with PROD ENV variables
        run: bundle exec fastlane ios distribute
        env:
          BETA_BUILD: true
          # sentry
          SENTRY_DIST: 0
          SENTRY_LOG_LEVEL: debug
          SENTRY_PROPERTIES: ${{ github.workspace }}/ios/sentry.properties
          SENTRY_RELEASE: alpha
          # app env variables
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY_STAGING }}
          APPSFLYER_API_KEY: ${{ secrets.APPSFLYER_API_KEY }}
          APP_METRICA_API_KEY: ${{ secrets.APP_METRICA_API_KEY_STAGING }}
          DATABASE_DEFAULT_ENCRYPTION_KEY: ${{ secrets.DATABASE_DEFAULT_ENCRYPTION_KEY }}
          OAUTH_CLIENT_ID_ANDROID: ${{ secrets.OAUTH_CLIENT_ID_ANDROID_STAGING }}
          OAUTH_CLIENT_ID_IOS: ${{ secrets.OAUTH_CLIENT_ID_IOS_STAGING }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
          REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}
          TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
          TIKTOK_APP_ID: ${{ secrets.TIKTOK_APP_ID }}
          # Fastlane env variables
          CURRENT_BRANCH: ${{ github.event.client_payload.branch }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FIREBASEAPPDISTRO_APP: ${{ secrets.FIREBASE_APP_ID_IOS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          CUSTOM_BUILD_NUMBER: ${{ github.run_number }}

      - uses: ./.github/actions/notify-gitlab
        if: always()
        with:
          gitlab-token: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

  distribute-apk:
    name: "🤖 Android Build & Distribute"
    needs: check_code_changes
    if: needs.check_code_changes.outputs.run_android_build == 'true'
    runs-on: ubuntu-24.04 # M1 not a really faster than x64
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: ./.github/actions/initial-setup
        with:
          ruby: ${{ env.RUBY_VERSION }}
          java: ${{ env.JAVA_VERSION }}

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}

      - name: Notify gitlab
        run: ./infrastructure/gitlab/status.sh "state=running&description=$GITHUB_RUN_ID"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

      - uses: ./.github/actions/android-keystores
        with:
          encrypt-password: ${{ secrets.ENCRYPT_PASSWORD }}

      - uses: ./.github/actions/install-dependencies

      - run: bundle install --jobs 4 --retry 3

      - name: Restore Gradle cache
        id: gradle-cache-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run fastlane line "fastlane android distribute" with PROD ENV variables
        run: bundle exec fastlane android distribute
        env:
          BETA_BUILD: true
          # sentry
          SENTRY_DIST: 0
          SENTRY_LOG_LEVEL: debug
          SENTRY_PROPERTIES: ${{ github.workspace }}/android/sentry.properties
          SENTRY_RELEASE: alpha
          # app env variables
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY_STAGING }}
          APPSFLYER_API_KEY: ${{ secrets.APPSFLYER_API_KEY }}
          APP_METRICA_API_KEY: ${{ secrets.APP_METRICA_API_KEY_STAGING }}
          DATABASE_DEFAULT_ENCRYPTION_KEY: ${{ secrets.DATABASE_DEFAULT_ENCRYPTION_KEY }}
          OAUTH_CLIENT_ID_ANDROID: ${{ secrets.OAUTH_CLIENT_ID_ANDROID_STAGING }}
          OAUTH_CLIENT_ID_IOS: ${{ secrets.OAUTH_CLIENT_ID_IOS_STAGING }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REVENUECAT_API_KEY_ANDROID: ${{ secrets.REVENUECAT_API_KEY_ANDROID }}
          REVENUECAT_API_KEY_IOS: ${{ secrets.REVENUECAT_API_KEY_IOS }}
          TIKTOK_ACCESS_TOKEN: ${{ secrets.TIKTOK_ACCESS_TOKEN }}
          TIKTOK_APP_ID: ${{ secrets.TIKTOK_APP_ID }}
          # Fastlane env variables
          CURRENT_BRANCH: ${{ github.event.client_payload.branch }}
          FIREBASEAPPDISTRO_APP: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Save Gradle cache
        if: steps.gradle-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ steps.gradle-cache-restore.outputs.cache-primary-key }}

      - uses: ./.github/actions/notify-gitlab
        if: always()
        with:
          gitlab-token: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}
