name: Code Quality (eslint, ts, jest)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: ["code-quality"]

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        # macos-26:     CPU: (3) arm64 Apple M1 (Virtual);            Memory: 89.83 MB / 7.00 GB
        # ubuntu-24.04: CPU: (4) x64 AMD EPYC 7763 64-Core Processor; Memory: 14.56 GB / 15.62 GB
        os: [ ubuntu-24.04 ] # macos-26 has when same performance as ubuntu-24.04 for this job
        nodejs: [ '24' ]

    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      # Required by `infrastructure/gitlab/status.sh`
      GIT_LAB_COMMIT_SHA: ${{ github.event.client_payload.commit_sha }}
      GIT_LAB_PIPELINE_ID: ${{ github.event.client_payload.pipeline_id }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ./.github/actions/initial-setup
        with:
          nodejs: ${{ matrix.nodejs }}

      - uses: ./.github/actions/clone-repo
        with:
          repo-url: ${{ secrets.REPO_URL }}
          user-name: ${{ secrets.GITLAB_USER_NAME }}
          user-email: ${{ secrets.GITLAB_USER_EMAIL }}
          ssh-known-host: ${{ secrets.SSH_KNOWN_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.event.client_payload.branch }}

      - name: Notify gitlab
        run: ./infrastructure/gitlab/status.sh "state=running&description=$GITHUB_RUN_ID"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

      - uses: ./.github/actions/install-dependencies

      - name: TypeScript
        run: yarn ts

      - name: Eslint
        run: yarn lint --quiet

      - name: Check i18n
        run: yarn check-i18n

      - name: Unit tests
        run: yarn test --ci


      #############################################################
      # NOTIFY GITLAB ABOUT JOB RESULT
      #############################################################
      - name: The job has cancelled
        if: ${{ cancelled() }}
        run: ./infrastructure/gitlab/status.sh "state=canceled"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

      - name: The job has failed
        if: ${{ failure() }}
        run: ./infrastructure/gitlab/status.sh "state=failed"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}

      - name: The job has success
        run: ./infrastructure/gitlab/status.sh "state=success"
        env:
          GIT_LAB_ACCESS_TOKEN: ${{ secrets.GIT_LAB_ACCESS_TOKEN }}
